services:
  nodejs:
    container_name: "nodejs"
    image: node:20.9.0
    working_dir: /home/nodejs
    command:
      - /bin/sh
      - -c
      - |
        wget https://github.com/naungsoe-yan/dev-assessment/archive/refs/heads/main.zip
        unzip -o main.zip
        rm main.zip
        npm install -g @nestjs/cli
        cd ./dev-assessment-main
        npm install
        npm run build
        cd ./dist
        node main.js
    environment:
      - NODE_ENV=production
    depends_on:
      - mysql
    links:
      - "mysql:database"
    ports:
      - "3000:3000"
    volumes:
      - nodejs:/home/nodejs
  mysql:
    container_name: "mysql"
    image: mysql:8.2.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql:/home/mysql
volumes:
  nodejs:
  mysql:
