services:
  nodejs:
    container_name: "nodejs"
    image: node:20.9.0
    working_dir: /home/nodejs
    command:
      - /bin/sh
      - -c
      - |
        curl https://codeload.github.com/naungsoe-yan/dev-assessment/zip/refs/heads/main --output main.zip
        unzip -o main.zip
        rm main.zip
        npm install -g @nestjs/cli
        cd ./dev-assessment-main
        npm install
        npm run start
    environment:
      NODE_ENV: development
    depends_on:
      - seeder
    links:
      - mysql
    ports:
      - "3000:3000"
    volumes:
      - nodejs:/home/nodejs
  seeder:
    container_name: "seeder"
    image: mysql:8.2.0
    entrypoint:
      - /bin/sh
      - -c
      - |
        sleep 30
        curl https://raw.githubusercontent.com/naungsoe-yan/dev-assessment/main/mysql-init.sql --output mysql-init.sql
        mysql --user=root --password=password --host=mysql --port=3306 dev-assessment < mysql-init.sql
        exit
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
    depends_on:
      - mysql
    links:
      - mysql
    ports:
      - "3305:3305"
    volumes:
      - mysql:/home/mysql
  mysql:
    container_name: "mysql"
    image: mysql:8.2.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: dev-assessment
    ports:
      - "3306:3306"
    volumes:
      - mysql:/home/mysql
volumes:
  nodejs:
  seeder:
  mysql:
