services:
  backend:
    container_name: "dev-assessment-mysql"
    image: node
    command: --default-authentication-plugin=mysql_native_password
    depends_on:
      - mysql
    links:
      - "mysql:database"
    ports:
      - "3000:3000"
    volumes:
      - backend:/home/node/nestjs
  mysql:
    container_name: "dev-assessment-mysql"
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql:/home/node/mysql
volumes:
  backend:
  mysql:
