services:
  mysql:
    container_name: "dev-assessment-mysql"
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql:/home/node/mysql
volumes:
  mysql:
